c_library('driver',
  sources = [
    'driver.cc',
  ],
  deps = [
    '//etl/stm32f4xx',
    '//demo/runtime',
  ],
)

c_library('api',
  sources = [
    'api.cc',
  ],
  deps = [
    '//etl/stm32f4xx',
    '//demo/runtime',
  ],
)

