c_library('k',
  sources = [
    'context.cc',
    'entry.S',
    'ipc.cc',
    'key.cc',
    'main.cc',
    'mm_fault.cc',
    'null_object.cc',
    'object_table.cc',
    'traps.cc',
    'svc.cc',
    'unprivileged.cc',
    'unprivileged.S',
  ],
  deps = [
    '//etl:assert_loop'
  ],
)
